<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Calificaciones</h5>
                <form action="" method="POST">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>No. De Control</th>
                            <th>Nombre</th>
                            <th>Calificación</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->alumnos as $alumno): ?>
                        <tr>
                            <td>
                            <label for="<?= $alumno->getNoDeControl() ?>">
                            <?= $alumno->getNoDeControl() ?>
                            </label>
                            </td>
                            <td>
                            <label for="<?= $alumno->getNoDeControl() ?>">
                            <?= $alumno->getNombre() ?>
                            </label>
                            </td>
                            <td>
                            <div class="row">
                                <div class="col-3">
                                <input 
                                    id="<?= $alumno->getNoDeControl() ?>" 
                                    class="form-control text-center"
                                    name="calificaciones[<?= $alumno->getNoDeControl() ?>]"
                                >
                                </div>
                            </div>
                            </th>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>

                <button class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>
</div>